name: Code, Design & Coffee
markdown: kramdown

permalink: /:year/:month/:title

encoding: utf-8

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed